# Generated by Django 5.2.8 on 2025-12-01 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('platform', models.CharField(default='instagram', max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('ready', 'Ready'), ('error', 'Error')], default='new', max_length=20)),
                ('original_text', models.TextField(blank=True)),
                ('transcript', models.TextField(blank=True)),
                ('generated_caption', models.TextField(blank=True)),
                ('generated_script', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('social_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='saas.socialaccount')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='saas.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
