# Generated by Django 5.2.8 on 2025-12-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0003_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='error_message',
            field=models.TextField(blank=True),
        ),
    ]
