# Generated by Django 5.2.8 on 2026-01-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0005_subscriptionplan_post_caption_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments_count',
            field=models.IntegerField(blank=True, help_text='Количество комментариев', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='engagement_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Процент вовлеченности (likes+comments+shares)/views * 100', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='likes_count',
            field=models.IntegerField(blank=True, help_text='Количество лайков', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Дата публикации оригинального контента', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='shares_count',
            field=models.IntegerField(blank=True, help_text='Количество репостов/шеров', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='video_duration',
            field=models.IntegerField(blank=True, help_text='Длительность видео в секундах', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.BigIntegerField(blank=True, help_text='Количество просмотров', null=True),
        ),
    ]
