# Generated by Django 5.2.8 on 2026-01-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0006_post_comments_count_post_engagement_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_followers',
            field=models.IntegerField(blank=True, help_text='Подписчики автора на момент парсинга', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='has_audio',
            field=models.BooleanField(blank=True, help_text='Есть ли аудиодорожка', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_video',
            field=models.BooleanField(blank=True, help_text='Является ли видео контентом', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='play_count',
            field=models.BigIntegerField(blank=True, help_text='Количество воспроизведений видео', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='saves_count',
            field=models.IntegerField(blank=True, help_text='Количество сохранений', null=True),
        ),
    ]
