# Generated by Django 5.2.8 on 2026-01-12 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0007_post_author_followers_post_has_audio_post_is_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('username', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_accounts', to='saas.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('workspace', 'platform', 'username')},
            },
        ),
    ]
