# Generated by Django 5.2.8 on 2026-01-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0008_competitoraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitoraccount',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube')], max_length=20),
        ),
    ]
