# Generated by Django 5.2.8 on 2026-01-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0009_alter_competitoraccount_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_scraping_enabled', models.BooleanField(default=True, verbose_name='Автоматический парсинг включен')),
                ('scraping_hour', models.IntegerField(default=9, help_text='Время в формате 24 часов', verbose_name='Час запуска парсинга (0-23)')),
                ('scraping_minute', models.IntegerField(default=0, verbose_name='Минута запуска парсинга (0-59)')),
                ('last_scraping_check', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки системы',
                'verbose_name_plural': 'Настройки системы',
            },
        ),
    ]
