# Generated by Django 5.2.8 on 2026-01-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0010_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='client_contact',
            field=models.CharField(blank=True, help_text='Email, телефон или Telegram', max_length=255, verbose_name='Контакт клиента'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='client_name',
            field=models.CharField(blank=True, help_text='Например: ООО "Ромашка" или Иван Петров', max_length=255, verbose_name='Название клиента/компании'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='client_notes',
            field=models.TextField(blank=True, verbose_name='Заметки о клиенте'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='color',
            field=models.CharField(default='#6366f1', help_text='HEX цвет, например #6366f1', max_length=7, verbose_name='Цвет для UI'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='is_client',
            field=models.BooleanField(default=False, help_text='Отметьте, если это workspace клиента', verbose_name='Клиентский проект'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
