# Generated by Django 5.2.8 on 2026-01-12 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0011_workspace_client_contact_workspace_client_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='tags',
            field=models.CharField(blank=True, help_text='Теги через запятую: срочно, премиум, активный', max_length=500, verbose_name='Теги'),
        ),
        migrations.CreateModel(
            name='WorkspaceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('note', 'Заметка'), ('call', 'Звонок'), ('meeting', 'Встреча'), ('email', 'Email'), ('post_created', 'Пост создан'), ('post_approved', 'Пост одобрен'), ('payment', 'Оплата'), ('other', 'Другое')], default='note', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_activities', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='saas.workspace')),
            ],
            options={
                'verbose_name': 'Активность клиента',
                'verbose_name_plural': 'Активности клиентов',
                'ordering': ['-created_at'],
            },
        ),
    ]
