# Generated by Django 5.2.8 on 2026-04-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0012_workspace_tags_workspaceactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='generated_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='generated_title',
            field=models.TextField(blank=True),
        ),
    ]
