# Generated by Django 5.2.8 on 2026-04-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0013_post_generated_description_post_generated_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='type',
            field=models.CharField(choices=[('caption', 'Caption'), ('script', 'Script'), ('title', 'Title'), ('description', 'Description'), ('other', 'Other')], default='caption', max_length=20),
        ),
    ]
