# Generated by Django 5.2.8 on 2026-04-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0014_alter_prompt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Используется при обработке постов кнопкой "Обработать"', verbose_name='Промпт по умолчанию'),
        ),
        migrations.AddConstraint(
            model_name='prompt',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('workspace', 'type'), name='unique_default_prompt_per_workspace_type'),
        ),
    ]
