# Generated by Django 5.2.8 on 2026-04-04 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0015_prompt_is_default_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='prompt',
            name='unique_default_prompt_per_workspace_type',
        ),
    ]
