# Generated by Django 5.2.8 on 2026-04-04 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0016_remove_prompt_unique_default_prompt_per_workspace_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prompt',
            unique_together=set(),
        ),
    ]
