# Generated by Django 5.2.8 on 2026-04-07 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0017_alter_prompt_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email приглашённого (опционально)')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='editor', max_length=10, verbose_name='Роль в воркспейсе')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('used', models.BooleanField(default=False, verbose_name='Использован')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invites', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invites', to=settings.AUTH_USER_MODEL, verbose_name='Кто использовал')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_tokens', to='saas.workspace', verbose_name='Воркспейс')),
            ],
            options={
                'verbose_name': 'Токен приглашения',
                'verbose_name_plural': 'Токены приглашений',
                'ordering': ['-created_at'],
            },
        ),
    ]
