# Generated by Django 5.2.8 on 2026-04-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0018_invitetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitoraccount',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn')], max_length=20),
        ),
        migrations.AlterField(
            model_name='invitetoken',
            name='role',
            field=models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('editor', 'Редактор'), ('viewer', 'Наблюдатель')], default='editor', max_length=10, verbose_name='Роль в воркспейсе'),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='role',
            field=models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('editor', 'Редактор'), ('viewer', 'Наблюдатель')], default='editor', max_length=10),
        ),
    ]
