# Generated by Django 5.2.8 on 2026-04-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0019_alter_competitoraccount_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='max_parse_depth',
            field=models.IntegerField(default=10, help_text='Максимальное количество публикаций для выкачивания из профиля (5-50)', verbose_name='Глубина парсинга профилей'),
        ),
    ]
