# Generated by Django 5.2.8 on 2026-04-11 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0021_postnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='max_api_calls_per_day',
            field=models.IntegerField(default=500, help_text='Лимит запросов к ScrapeCreators API на пользователя в сутки', verbose_name='Макс. API-вызовов в день'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='max_workspaces_per_user',
            field=models.IntegerField(default=5, help_text='Сколько воркспейсов может создать один пользователь', verbose_name='Макс. воркспейсов на пользователя'),
        ),
        migrations.CreateModel(
            name='ApiCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_call_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог API-вызова',
                'verbose_name_plural': 'Логи API-вызовов',
                'ordering': ['-created_at'],
            },
        ),
    ]
