# Generated by Django 5.2.8 on 2026-04-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0022_systemsettings_max_api_calls_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, help_text='Описание поста/видео'),
        ),
    ]
