"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os
from dotenv import load_dotenv
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError(
        "SECRET_KEY is not set in environment variables. "
        "Please set SECRET_KEY in your .env file or environment."
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('1', 'true', 'yes')

# Allow hosts from env or default empty list
ALLOWED_HOSTS = [h for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h]

# Security settings for reverse proxy (Caddy)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
CSRF_TRUSTED_ORIGINS = [
    "https://78.17.34.15.sslip.io",
    "https://api.78.17.34.15.sslip.io",
    "http://localhost:3000",
]

# Application definition

INSTALLED_APPS = [
    # стандартные
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # сторонние
    'rest_framework',
    'corsheaders',

    # наши
    'saas',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # дальше стандартные
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
MIDDLEWARE.insert(0, 'corsheaders.middleware.CorsMiddleware')

# Allow CORS origins from env (comma-separated) or default localhost during development
env_cors = os.getenv('CORS_ALLOWED_ORIGINS', '')
if env_cors:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in env_cors.split(',') if o.strip()]
else:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]

# SECURITY: Never allow all origins in production
# This is strictly a development convenience and should NEVER be True in production
CORS_ALLOW_ALL_ORIGINS = False

# Debug: print resolved CORS settings at startup so we can verify in logs
try:
    print(f"CORS_ALLOWED_ORIGINS={CORS_ALLOWED_ORIGINS}")
    print(f"CORS_ALLOW_ALL_ORIGINS={CORS_ALLOW_ALL_ORIGINS}")
    logger.info('CORS_ALLOWED_ORIGINS=%s', CORS_ALLOWED_ORIGINS)
    logger.info('CORS_ALLOW_ALL_ORIGINS=%s', CORS_ALLOW_ALL_ORIGINS)
except Exception:
    pass

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

CELERY_BROKER_URL = os.getenv('REDIS_URL', os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0'))
CELERY_RESULT_BACKEND = os.getenv('REDIS_URL', os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0'))
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Debug / safety: print resolved Redis URLs at startup so logs show what the app will use.
import logging
logger = logging.getLogger(__name__)
try:
    # Also print to stdout to ensure visibility before logging is configured
    print(f"CELERY_BROKER_URL={CELERY_BROKER_URL}")
    print(f"CELERY_RESULT_BACKEND={CELERY_RESULT_BACKEND}")
    logger.info('CELERY_BROKER_URL=%s', CELERY_BROKER_URL)
    logger.info('CELERY_RESULT_BACKEND=%s', CELERY_RESULT_BACKEND)
    if CELERY_BROKER_URL.startswith('redis://localhost'):
        logger.warning('CELERY_BROKER_URL resolves to localhost; ensure REDIS_URL secret is set in deployment')
except Exception:
    # Never fail imports because of logging in settings
    pass

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
OPENAI_MODEL = os.getenv('OPENAI_MODEL', 'gpt-4o-mini')
OPENAI_API_BASE = os.getenv('OPENAI_API_BASE', 'https://api.openai.com/v1')
OPENAI_PROXY = os.getenv('OPENAI_PROXY')  # может быть None

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    # Rate limiting / Throttling
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '10/hour',     # Неаутентифицированные: 10 запросов/час (только логин/регистрация)
        'user': '1000/hour',   # Аутентифицированные: 1000 запросов/час
        'scrape': '50/hour',   # Парсинг: 50 запросов/час на пользователя
    },
}


WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# If DATABASE_URL is provided (e.g., postgres in production), use it to configure
# the default database. Prefer dj-database-url when available, otherwise fall
# back to a minimal parser.
DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
    try:
        import dj_database_url
        DATABASES['default'] = dj_database_url.parse(DATABASE_URL, conn_max_age=600)
        print('Using DATABASE_URL for database configuration')
    except Exception:
        # Minimal fallback parsing for postgres:// URLs
        from urllib.parse import urlparse
        result = urlparse(DATABASE_URL)
        if result.scheme and result.scheme.startswith('postgres'):
            DATABASES['default'] = {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': result.path.lstrip('/'),
                'USER': result.username,
                'PASSWORD': result.password,
                'HOST': result.hostname,
                'PORT': result.port or '',
            }
            print('Using DATABASE_URL (fallback parser) for database configuration')

# SECURITY: SQLite is NOT allowed in production (DEBUG=False)
if not DEBUG and DATABASES['default']['ENGINE'] == 'django.db.backends.sqlite3':
    raise ValueError(
        "SQLite is not allowed in production. "
        "Please set DATABASE_URL environment variable to a PostgreSQL connection string. "
        "Example: DATABASE_URL=postgres://user:pass@host:5432/dbname"
    )



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'
STATICFILES_DIRS = []
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Simple JWT settings (configurable via env)
ACCESS_MINUTES = int(os.getenv('SIMPLE_JWT_ACCESS_MINUTES', '60'))
REFRESH_DAYS = int(os.getenv('SIMPLE_JWT_REFRESH_DAYS', '30'))

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=ACCESS_MINUTES),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=REFRESH_DAYS),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
}
INSTALLED_APPS += ['rest_framework_simplejwt.token_blacklist']
